Use SSH instead of HTTPS for cloning
I had the following error:
    * transfer closed with outstanding read data remaining
    * Closing connection 0
    error: RPC failed; curl 18 transfer closed with outstanding read data remaining
    fatal: the remote end hung up unexpectedly
    fatal: protocol error: bad pack header